# Jekyll configuration

name: congusbongusgames
description: Game dev and rubbish

# url is currently only used only for the RSS feed in feed.xml
url: http://cxong.github.io

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''

# This can be '' to hide the Github nav button
github: 'cxong'

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: 'congusbongusgames'
comments: true

permalink: /:year/:month/:title
paginate: 3

exclude: ['README.md', 'LICENSE']

gems:
  - jemoji

markdown: kramdown
